name: Tests QCM AI E4

on:
  push:
    branches:
      - master
      - main

  pull_request:
    branches:
      - master
      - main

jobs:
  tests:

    runs-on: ubuntu-latest

    steps:

      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Installer Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Installer les dépendances
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Vérifier pytest
        run: |
          python -m pip show pytest

      - name: Lancer les tests
        run: |
          python -m pytest